[project]
name            = "pykeepass-stubs"
version         = "0.1.0"
description     = "Type stubs for pykeepass"
readme          = "README.md"
requires-python = ">=3.14"
classifiers     = []
dependencies    = ["types-lxml>=2026.2.16"]   # "lxml>=6.0.2"

[[project.authors]]
name  = "Kaj Kowalski"
email = "info@kajkowalski.nl"

[build-system]
requires      = ["uv_build>=0.10.2,<0.11.0"]
build-backend = "uv_build"

[tool.ruff.lint]
ignore = ["PYI029"]
